baseURL = "http://didalamkotak.netlify.app"
languageCode = "en-us"
title = "B-lowBox"
# title = "Ian Syah"
themesDir   = "themes"
theme       = "kotak"
enableEmoji = true
disqusShortname = "didalamkotak-netlify-app"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "home section"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "linux"
    name = "Linux"
    title = "linux section"
    url = "/categories/linux"
    weight = -110

    [[menu.main]]
    identifier = "windows"
    name = "Windows"
    title = "windows section"
    url = "/categories/windows"
    weight = -110

[Author]
    name    = "Oktavian Yoga"
    bio     = "Ordinary Student"
    avatar  = "img/MyAvatar.png"

[Params]
    subtitle = ""
    copyright   = "All rights reserved"
    opengraph   = true
    schema      = true
    readmore = false # Show "Read more" button in list if true
    authorbox = true # Show authorbox at bottom of pages if true
    toc = true # Enable Table of Contents
    pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
    post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
    mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["languages", "categories"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  #widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]


[Params.logo]
  image = "img/logoBaru.png" # Logo image. Path relative to "static"
  title = "B-Low Box" # Logo title, otherwise will use site title
  #subtitle = "College Documentation"

[Params.style.vars]
    highlightColor = "#fff400" # Override highlight color
    # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
    # Take care of different quotes OR escaping symbols in these params if necessary
    fontFamilyPrimary = "Roboto, Helvetica, Arial, sans-serif"
    fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
    # Enable parts of social widget
    #facebook = "username"
    twitter = "iansyah"
    instagram = "yogatra29"
    #linkedin = "username"
    telegram = "yogatra29"
    github = "Ian-syah"
    #gitlab = "username"
    #bitbucket = "username"
    email = "okta.yoga.syah@egmail.com.com"
