baseURL: 'http://dalamkotak.netlify.app'
languageCode: en-us
title: DalamKotak
enableEmoji: true
disqusShortname: didalamkotak-netlify-app
paginate: 6
enableRobotsTXT: true
menu:
  main:
    - identifier: home
      name: Home
      title: home section
      url: /
      weight: -110
    - identifier: linux
      name: Linux
      title: linux section
      url: /categories/linux
      weight: -110
    - identifier: windows
      name: Windows
      title: windows section
      url: /categories/windows
      weight: -110
Author:
  name: Oktoala
  bio: Ordinary Student
  avatar: img/codoala.png
Params:
  subtitle: ''
  copyright: All rights reserved
  opengraph: true
  readmore: false
  authorbox: true
  toc: true
  pager: true
  post_meta:
    - author
    - date
    - categories
    - translations
  mainSections:
    - post
    - blog
    - news
  sidebar:
    home: right
    list: right
    single: true
    widgets:
      - languages
      - categories
  logo:
    image: img/logoBaru.png
    title: Dalam Kotak
  style:
    vars:
      highlightColor: '#fff400'
      fontFamilyPrimary: "Quicksand, Roboto, Helvetica, Arial, sans-serif"
      fontFamilySecondary: "Domine, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
  widgets:
    recent_num: 5
    tags_counter: true
    social:
      twitter: iansyah
      instagram: yogatra29
      telegram: yogatra29
      github: oktoala
      email: okta.yoga.syah@egmail.com
